services:
  api:
    image: stumpisuter/parent-tracking-api:latest
    build: ./src
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./src/api:/usr/src/app
    labels:
      # Enable Traefik for this specific "backend" service
      - traefik.enable=true
      # Define the port inside of the Docker service to use
      - traefik.http.services.app.loadbalancer.server.port=8000
      # Use the traefik-public network (declared below)
      - traefik.docker.network=traefik-public
      - traefik.http.routers.app-http.middlewares=https-redirect
    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik-public

  view:
    image: stumpisuter/parent-tracking-frontend:latest
    build: ./src/frontend
    ports:
      - 3000:3000
    command: node build/index.js
    environment:
      NODE_ENV: production
      PUBLIC_HAKESCH_API_PATH: "/api"
    labels:
      # Enable Traefik for this specific "backend" service
      - traefik.enable=true
      # Define the port inside of the Docker service to use
      - traefik.http.services.app.loadbalancer.server.port=3000
      # Use the traefik-public network (declared below)
      - traefik.docker.network=traefik-public
      - traefik.http.routers.app-http.middlewares=https-redirect
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
