# https://taskfile.dev - For Parent-Tracking

tasks:
  init:
    cmds:
      - task: init-frontend

  init-frontend:
    dir: src/frontend
    cmds:
      - npm i

  dev:
    cmds:
      - docker compose up --build

  dev-frontend:
    dir: src/frontend
    cmds:
      - npm run dev

  build:
    cmds:
      - docker compose build
  
  build-frontend:
    dir: src/frontend
    cmds:
      - npm run build

  push:
    cmds:
      - task: build
      - docker compose push
