name: Docker Compose Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLIC_KEYCLOAK_URL: ${{ secrets.PUBLIC_KEYCLOAK_URL }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      AUTH_KEYCLOAK_ID: ${{ secrets.AUTH_KEYCLOAK_ID }}
      AUTH_KEYCLOAK_ISSUER: ${{ secrets.AUTH_KEYCLOAK_ISSUER }}
      PUBLIC_HAKESCH_API_PATH: ${{ env.PUBLIC_HAKESCH_API_PATH }}
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "docker-compose.yml"
