name: Docker Compose Action

on: []

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLIC_KEYCLOAK_URL: ${{ secrets.PUBLIC_KEYCLOAK_URL }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      AUTH_KEYCLOAK_ID: ${{ secrets.AUTH_KEYCLOAK_ID }}
      AUTH_KEYCLOAK_ISSUER: ${{ secrets.AUTH_KEYCLOAK_ISSUER }}
      PUBLIC_HAKESCH_API_PATH: "/api"
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Prepare Environment Variables for Deployment
        id: prepare-env
        run: |
          # Convert repository or organization variables to JSON format
          echo '${{ toJSON(vars) }}' > env_vars.json

          # Convert JSON to .env format
          cat env_vars.json | jq -r 'to_entries | map("\(.key)=\(.value)") | .[]' > src/frontend/.env

          #remove no longer needed env_vars.json file
          rm -f env_vars.json

          # Display the contents of the .env file (for debugging purposes)
          cat src/frontend/.env

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "docker-compose.yml"
        env:
          PUBLIC_KEYCLOAK_URL: ${{ secrets.PUBLIC_KEYCLOAK_URL }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          AUTH_KEYCLOAK_ID: ${{ secrets.AUTH_KEYCLOAK_ID }}
          AUTH_KEYCLOAK_ISSUER: ${{ secrets.AUTH_KEYCLOAK_ISSUER }}
          PUBLIC_HAKESCH_API_PATH: "/api"
